package prueba_Hibernate;
// Generated 12 dic 2025, 9:01:05 by Hibernate Tools 6.4.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dept generated by hbm2java
 */
public class Dept implements java.io.Serializable {

	private Integer deptno;
	private String loc;
	private String deptname;
	private Set emps = new HashSet(0);

	public Dept() {
	}

	public Dept(String loc, String deptname, Set emps) {
		this.loc = loc;
		this.deptname = deptname;
		this.emps = emps;
	}

	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set emps) {
		this.emps = emps;
	}

}
