package prueba_Hibernate;
// Generated 12 dic 2025, 9:01:05 by Hibernate Tools 6.4.8.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Emp generated by hbm2java
 */

public class Emp implements java.io.Serializable {

	private Integer empno;
	private Sals sals;
	private Emp emp;
	private Dept dept;
	private String ename;
	private Date hiredate;
	private String job;
	private Set emps = new HashSet(0);
	private Set proyectoses = new HashSet(0);

	public Emp() {
	}

	public Emp(Sals sals, Emp emp, Dept dept, String ename, Date hiredate, String job, Set emps, Set proyectoses) {
		this.sals = sals;
		this.emp = emp;
		this.dept = dept;
		this.ename = ename;
		this.hiredate = hiredate;
		this.job = job;
		this.emps = emps;
		this.proyectoses = proyectoses;
	}

	public Integer getEmpno() {
		return this.empno;
	}

	public void setEmpno(Integer empno) {
		this.empno = empno;
	}

	public Sals getSals() {
		return this.sals;
	}

	public void setSals(Sals sals) {
		this.sals = sals;
	}

	public Emp getEmp() {
		return this.emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set<Emp> emps) {
		this.emps = emps;
	}

	public Set getProyectoses() {
		return this.proyectoses;
	}

	public void setProyectoses(Set proyectoses) {
		this.proyectoses = proyectoses;
	}
	
	@Override
	public String toString() {
		if (this.getEmps() != null) {
			return "Empleado: " + getEmpno() + " Nombre: " + getEname() + " Puesto: " + getJob() + " Manager: " +
					" Salario: " +  getSals() + " Departamento: " + getDept() + " Proyectos: " + getProyectoses();
		} else {
			return "Empleado: " + getEmpno() + " Nombre: " + getEname() + " Puesto: " + getJob() + " Manager: No tiene" + 
					" Salario: " +  getSals() + " Departamento: " + getDept() + " Proyectos: " + getProyectoses();
		}

}
}
