package prueba_Hibernate;
// Generated 12 dic 2025, 9:01:05 by Hibernate Tools 6.4.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos implements java.io.Serializable {

	private Integer idProyecto;
	private String nombreProyecto;
	private Set emps = new HashSet(0);

	public Proyectos() {
	}

	public Proyectos(String nombreProyecto, Set emps) {
		this.nombreProyecto = nombreProyecto;
		this.emps = emps;
	}

	public Integer getIdProyecto() {
		return this.idProyecto;
	}

	public void setIdProyecto(Integer idProyecto) {
		this.idProyecto = idProyecto;
	}

	public String getNombreProyecto() {
		return this.nombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set emps) {
		this.emps = emps;
	}

}
