package prueba_Hibernate;
// Generated 12 dic 2025, 9:01:05 by Hibernate Tools 6.4.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sals generated by hbm2java
 */
public class Sals implements java.io.Serializable {

	private int grade;
	private Integer quantity;
	private Set emps = new HashSet(0);

	public Sals() {
	}

	public Sals(int grade) {
		this.grade = grade;
	}

	public Sals(int grade, Integer quantity, Set emps) {
		this.grade = grade;
		this.quantity = quantity;
		this.emps = emps;
	}

	public int getGrade() {
		return this.grade;
	}

	public void setGrade(int grade) {
		this.grade = grade;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Set getEmps() {
		return this.emps;
	}

	public void setEmps(Set emps) {
		this.emps = emps;
	}

}
